import type { StoryTag } from "@app-types/data";

export const STORY_TAGS: StoryTag[] = [
  "fantasy",
  "exploration",
  "sci-fi",
  "adventure",
  "mystery",
  "romance",
  "horror",
  "comedy",
  "drama",
  "thriller",
  "historical",
  "slice-of-life",
  "supernatural",
  "psychological",
  "cyberpunk",
  "post-apocalyptic",
  "steampunk",
  "dark-fantasy",
  "mythology",
  "detective",
  "time-travel",
  "coming-of-age",
  "tragedy",
  "survival",
  "dystopian",
  "political",
  "satire",
  "crime",
  "war",
  "magic-realism",
  "philosophical",
  "hopeful",
  "bittersweet",
  "melancholy",
  "uplifting",
  "dark",
  "whimsical",
  "romantic-comedy",
  "tragic-romance",
  "existential",
  "introspective",
  "urban",
  "rural",
  "space",
  "underwater",
  "desert",
  "forest",
  "mountain",
  "island",
  "cityscape",
  "castle",
  "ancient",
  "medieval",
  "renaissance",
  "industrial",
  "modern",
  "near-future",
  "far-future",
  "timeless",
  "alternate-history",
  "prehistoric",
  "nonlinear",
  "episodic",
  "parallel-universe",
  "multiple-endings",
  "dreamlike",
  "metafiction",
  "found-footage",
  "mystical-journey",
  "redemption",
  "betrayal",
  "antihero",
  "hero's-journey",
  "villain-protagonist",
  "ensemble-cast",
  "loner",
  "mentor-apprentice",
  "chosen-one",
  "tragic-hero",
  "outsider",
  "rebel",
  "noir",
  "gothic",
  "romantic",
  "epic",
  "lighthearted",
  "grimdark",
  "suspenseful",
  "chill",
  "cozy",
  "mystical",
  "sports",
  "music",
  "school-life",
  "virtual-reality",
  "isekai",
  "mecha",
  "spy",
  "heist",
  "detective-noir",
  "monster-hunter",
];

export const STORY_TAG_LABELS_DICT: Record<StoryTag, string> = {
  fantasy: "Fantasy",
  exploration: "Exploration",
  "sci-fi": "Sci-Fi",
  adventure: "Adventure",
  mystery: "Mystery",
  romance: "Romance",
  horror: "Horror",
  comedy: "Comedy",
  drama: "Drama",
  thriller: "Thriller",
  historical: "Historical",
  "slice-of-life": "Slice of Life",
  supernatural: "Supernatural",
  psychological: "Psychological",
  cyberpunk: "Cyberpunk",
  "post-apocalyptic": "Post-Apocalyptic",
  steampunk: "Steampunk",
  "dark-fantasy": "Dark Fantasy",
  mythology: "Mythology",
  detective: "Detective",
  "time-travel": "Time Travel",
  "coming-of-age": "Coming of Age",
  tragedy: "Tragedy",
  survival: "Survival",
  dystopian: "Dystopian",
  political: "Political",
  satire: "Satire",
  crime: "Crime",
  war: "War",
  "magic-realism": "Magic Realism",
  philosophical: "Philosophical",
  hopeful: "Hopeful",
  bittersweet: "Bittersweet",
  melancholy: "Melancholy",
  uplifting: "Uplifting",
  dark: "Dark",
  whimsical: "Whimsical",
  "romantic-comedy": "Romantic Comedy",
  "tragic-romance": "Tragic Romance",
  existential: "Existential",
  introspective: "Introspective",
  urban: "Urban",
  rural: "Rural",
  space: "Space",
  underwater: "Underwater",
  desert: "Desert",
  forest: "Forest",
  mountain: "Mountain",
  island: "Island",
  cityscape: "Cityscape",
  castle: "Castle",
  ancient: "Ancient",
  medieval: "Medieval",
  renaissance: "Renaissance",
  industrial: "Industrial",
  modern: "Modern",
  "near-future": "Near Future",
  "far-future": "Far Future",
  timeless: "Timeless",
  "alternate-history": "Alternate History",
  prehistoric: "Prehistoric",
  nonlinear: "Nonlinear",
  episodic: "Episodic",
  "parallel-universe": "Parallel Universe",
  "multiple-endings": "Multiple Endings",
  dreamlike: "Dreamlike",
  metafiction: "Metafiction",
  "found-footage": "Found Footage",
  "mystical-journey": "Mystical Journey",
  redemption: "Redemption",
  betrayal: "Betrayal",
  antihero: "Antihero",
  "hero's-journey": "Hero's Journey",
  "villain-protagonist": "Villain Protagonist",
  "ensemble-cast": "Ensemble Cast",
  loner: "Loner",
  "mentor-apprentice": "Mentor & Apprentice",
  "chosen-one": "Chosen One",
  "tragic-hero": "Tragic Hero",
  outsider: "Outsider",
  rebel: "Rebel",
  noir: "Noir",
  gothic: "Gothic",
  romantic: "Romantic",
  epic: "Epic",
  lighthearted: "Lighthearted",
  grimdark: "Grimdark",
  suspenseful: "Suspenseful",
  chill: "Chill",
  cozy: "Cozy",
  mystical: "Mystical",
  sports: "Sports",
  music: "Music",
  "school-life": "School Life",
  "virtual-reality": "Virtual Reality",
  isekai: "Isekai",
  mecha: "Mecha",
  spy: "Spy",
  heist: "Heist",
  "detective-noir": "Detective Noir",
  "monster-hunter": "Monster Hunter",
};
